name: Generate Zip File

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
        path: VTuberStudio
        submodules: true
    - name: zip up contents
      shell: bash
      run: |
        VERSION=`echo "$GITHUB_REF_NAME" | sed "s%/%.%g"`
        ZIP_FILE_NAME=VTuberStudio.$VERSION.zip
        zip -8 -r $ZIP_FILE_NAME VTuberStudio -x '*.git*'
        echo "zip_file_name=$ZIP_FILE_NAME" >> $GITHUB_ENV

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.zip_file_name }}" 
